# docker-compose.yml
# Local development option alongside Azure Pipeline deployment

version: '3.8'

services:
  talk4finance:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GPT_API_KEY: ${GPT_API_KEY}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/talk4finance.db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - GPT_API_KEY=${GPT_API_KEY}
      - POWERBI_DATASET_ID=${POWERBI_DATASET_ID}
      - POWERBI_WORKSPACE_ID=${POWERBI_WORKSPACE_ID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  talk4finance_data:
    driver: local